@startsalt
{+
    {* <b>Plataforma de Auditoría Ciudadana</b> | [Dashboard] | [Políticos] | [Leyes] | [Admin] | ( ) Buscar político... }
    --
    {+
        {/ <b>Perfil del Político</b> }
        {
            { [ ( Foto ) ] } | {
                <b>Nombre:</b> Juanito Perez Tapioca
                <b>Partido:</b> Movimiento Transparencia
                <b>Cargo:</b> Asambleísta Nacional
                <b>Patrimonio:</b> $120,000.00
                [ Ver Antecedentes ]
            }
        }
    }
    --
    {
        .
        <b>Métrica de Coherencia (RF-04/05)</b>
        {
            { (O) 85% Coherente } | { [######....] 8.5/10 }
        }
        .
    }
    --
    {#
        <b>Historial de Coherencia (Promesas vs Votos)</b>
        [Propuesta de Ley ] | [Voto Real] | [Resultado ] | [Análisis ]
        "Reducción de Impuestos" | A FAVOR | (V) Coherente | "Cumple promesa de campaña 2023"
        "Protección de Páramos" | ABSTENCION | (X) Incoherente | "Voto no alineado a propuesta ambiental"
        "Reforma Educativa" | A FAVOR | (V) Coherente | "Alineado con plan de gobierno"
    }
    --
    {
        <b>Participación Ciudadana (RF-06)</b>
        {
            Tu calificación: | [ ( ) 1 | ( ) 2 | ( ) 3 | (X) 4 | ( ) 5 ]
            Comentario: | "Me parece coherente su votación en educación."
            [ Publicar Comentario ]
        }
        {
            User1250 le da este politico: | [ ( ) 1 | ( ) 2 | ( ) 3 | (X) 4 | ( ) 5 ]
            Comentario: | "No me gusta la forma en la que hizo....."
            [ LIKE ]  | [ COMENTAR ]
        }
    }
}
@endsalt